### ISSUE TITLE
🐛 [24.10.24] 로그인 이슈

### ISSUE THREAD

**Issue by lumpenop** [Mt-NextJs/linkle#152]
## 문제 상황

- 현재는 세션 스토리지에 토큰 존재 여부만 확인하는 것으로 로그인/비 로그인 상태를 구분하고 있어, 세션 종료시 토큰 삭제 하는 로직을 추가해야 할 것 같습니다

## 재현 가능 여부

- [ ] 예
- [ ] 아니오

**Comment by s-ja** [comment]
현재는 로그인 이후 세션과 쿠키에 모두 토큰 저장중입니다.
제가 만든 미들웨어 코드도 그렇고, SSR 활용에 쿠키가 유리할 것 같아 이후에 일괄적으로 적용할 예정입니다.
곧 작업할 API 호출부 분리 과정에서 같이 진행할 수 있을것 같아요.
