### ISSUE TITLE
✨ [24.11.26] 메인 페이지 레아이웃(스타일) 조정

### ISSUE THREAD

**Issue by s-ja** [Mt-NextJs/linkle#281]
## Todo

- [x] 다크모드 조정
- [x] 반응형 디자인 구현
- [x] 레이아웃 조정

## 기타

- admin 페이지와의 비교 같이 작업 진행 필요 예상

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

This change implements dark mode adjustments, responsive design, and layout adjustments for the Linkle project. It modifies the global CSS, Tailwind config, theme toggle component, and theme provider to improve the overall user experience and visual consistency across different screen sizes and themes.

You can review changes in this commit: https://github.com/lkilu6456546/Mt-NextJs-linkle-281/commit/8a53c03097023ff8f035e06539d18e8f5b88d7ad.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by s-ja** [comment]
추가 세부 조정 필요
