### ISSUE TITLE
🐛 [24.10.14] api 테스트 관련 cors 오류

### ISSUE THREAD

**Issue by Defor721** [Mt-NextJs/linkle#30]
## 문제 상황
  - 로그인 api 테스트 중 cors 오류 발생

## 재현 가능 여부

- [x] 예
- [ ] 아니오

## 코드
- 에러 코드
"Access to fetch at 'http://43.201.21.97:3002/login' from origin 'http://localhost:3000/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

- api 코드
![qqdqdqdq](https://github.com/user-attachments/assets/b9400045-7bfd-4ad4-8903-d8a277c45be9)

**Comment by lumpenop** [comment]
프록시로 우회할 수 있다고 하여 config 설정을 해보았으나 마찬가지로 cors 에러 발생하였습니다.
